server:
  port: 9000
  
spring:
  datasource:
    url: jdbc:oracle:thin:@abcfitness.duckdns.org:22360:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: exercise
    password: 92949597

mybatis:
  mapper-locations:
  - mapper/**/*.xml
  type-aliases-package: com.project.file.model